from __future__ import annotations

import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from dotenv import load_dotenv

LAST_ENV_PATH = None  # para debug

def carregar_variaveis_ambiente():

    global LAST_ENV_PATH
    load_dotenv(override=False)  # passo 1

    candidates: List[Path] = []
    try:
        if getattr(sys, 'frozen', False):
            base_dir = Path(sys.executable).parent
            meipass = Path(getattr(sys, '_MEIPASS', base_dir))
            candidates += [base_dir / '.env', meipass / '.env']
        else:
            base_dir = Path(__file__).parent
            candidates += [base_dir / '.env']
    except Exception:
        pass

    candidates.append(Path.cwd() / '.env')  # passo 3

    for p in candidates:
        if p.exists():
            load_dotenv(dotenv_path=p, override=True)
            LAST_ENV_PATH = str(p)
            break

def obter_config_banco() -> dict:
    """Lê credenciais/ajustes do .env (carregado por carregar_variaveis_ambiente)."""
    carregar_variaveis_ambiente()
    cfg = {
        'host'    : os.getenv('DB_HOST', ''),
        'user'    : os.getenv('DB_USER', ''),
        'password': os.getenv('DB_PASSWORD', ''),
        'database': os.getenv('DB_DATABASE', ''),
        'port'    : int(os.getenv('DB_PORT', '3306')),
        'timeout' : int(os.getenv('DB_TIMEOUT', '15')),
    }
    # opcionais
    auth_plugin = os.getenv('DB_AUTH_PLUGIN', '').strip()   # ex: mysql_native_password
    if auth_plugin:
        cfg['auth_plugin'] = auth_plugin
    ssl_ca   = os.getenv('DB_SSL_CA', '').strip()
    ssl_cert = os.getenv('DB_SSL_CERT', '').strip()
    ssl_key  = os.getenv('DB_SSL_KEY', '').strip()
    if ssl_ca:
        cfg['ssl_ca'] = ssl_ca
    if ssl_cert:
        cfg['ssl_cert'] = ssl_cert
    if ssl_key:
        cfg['ssl_key'] = ssl_key
    return cfg

# Colunas esperadas em thproc (na ordem exata para o INSERT)
colunas_thproc = [
    'cnj', 'tipoPartePoloAtivo', 'partePoloAtivo', 'tipoPartePoloPassivo',
    'partePoloPassivo', 'cliente', 'tipoDeRito', 'dataDistribuicao',
    'numeroUnidade', 'unidade', 'especialidade', 'comarca', 'estado',
    'orgao', 'natureza', 'materia', 'dataInstancia', 'tipoInstancia',
    'valorCausa', 'tipoAcao', 'tipoObjeto', 'dataFase', 'fase', 'dataStatus',
    'status', 'carteira', 'prioridadeDe', 'dataEvento', 'tipoEvento',
    'descricaoEvento', 'solicitanteEvento', 'responsavelEvento',
    'corresponsavel', 'teste', 'pasta', 'numeroProcessoAnterior',
    'numeroProcessoCNJ', 'sistemaExterno', 'processoEletronico',
    'processoEstrategico', 'grupoProcesso', 'complementoEvento',
    'observacaoEvento', 'grupoTrabalho', 'dataNotificacao',
    'dataNotificacaoAdicional', 'probabilidadePerda',
    'dataValorProvisionado', 'valorProvisionado', 'dataAndamento',
    'tipoAndamento', 'descricaoAndamento', 'complementoAndamento',
    'solicitanteAndamento', 'responsavelAndamento', 'corresponsavelAndamento',
    'descricaoObjeto', 'escritorioCredenciado', 'data_hora_verificacao',
    'usuario_verificado_id', 'verificado', 'nomegrupo_id', 'cliente_id',
    'exportado', 'dataContratacao', 'observacaoDoProcesso',
    'parecerDoProcesso', 'data_hora_submit', 'data_hora_export',
    'usuario_submit_id', 'usuario_export_id', 'valorFinalCausa',
    'tipoPoloCliente', 'data_resultado', 'tipo_resultado',
    'descricao_resultado', 'Adv_parte_contraria', 'codnatureza',
    'codparte_polo_ativo', 'codpolo_cliente', 'codsistema_externo',
    'codstatus', 'codfase', 'codespecialidade', 'codorgao', 'codmateria',
    'codtipo_rito', 'codcomarca', 'codparte_polo_passivo', 'codunidade',
    'codtipo_instancia', 'codcorresponsavelAndamento', 'codlote'
]

colunas_thproc_regular = colunas_thproc + ['excluido']

# Mapeamento de renome da planilha -> colunas do banco
RENAME_MAP = {
    'Pasta': 'pasta',
    'Nº do Processo Anterior': 'numeroProcessoAnterior',
    'Nº do Processo CNJ': 'cnj',
    'Tipo de Parte Pólo Ativo': 'tipoPartePoloAtivo',
    'Parte Pólo Ativo': 'partePoloAtivo',
    'Tipo de Parte Pólo Passivo': 'tipoPartePoloPassivo',
    'Parte Pólo Passivo': 'partePoloPassivo',
    'Cliente': 'cliente',
    'Tipo de Rito': 'tipoDeRito',
    'Data de Distribuição': 'dataDistribuicao',
    'Número Unidade': 'numeroUnidade',
    'Unidade': 'unidade',
    'Especialidade': 'especialidade',
    'Comarca': 'comarca',
    'Estado': 'estado',
    'Órgão': 'orgao',
    'Natureza': 'natureza',
    'Matéria': 'materia',
    'Data da Instância': 'dataInstancia',
    'Tipo de Instância': 'tipoInstancia',
    'Sistema Externo': 'sistemaExterno',
    'Processo Eletrônico': 'processoEletronico',
    'Processo Estratégico': 'processoEstrategico',
    'Valor da Causa': 'valorCausa',
    'Valor Final da Causa': 'valorFinalCausa',
    'Tipo de Ação': 'tipoAcao',
    'Tipo de Objeto': 'tipoObjeto',
    'Data da Fase': 'dataFase',
    'Fase': 'fase',
    'Data do Status': 'dataStatus',
    'Status': 'status',
    'Grupo de Processo': 'grupoProcesso',
    'Prioridade De': 'prioridadeDe',
    'Data do Resultado': 'data_resultado',
    'Tipo de Resultado': 'tipo_resultado',
    'Descrição do Resultado': 'descricao_resultado',
    'Data Evento': 'dataEvento',
    'Tipo Evento': 'tipoEvento',
    'Descrição Evento': 'descricaoEvento',
    'Complemento Evento': 'complementoEvento',
    'Observação Evento': 'observacaoEvento',
    'Solicitante Evento': 'solicitanteEvento',
    'Responsável Evento': 'responsavelEvento',
    'Grupo de Trabalho': 'grupoTrabalho',
    'Corresponsável': 'corresponsavel',
    'Data de Notificação': 'dataNotificacao',
    'Data de Notificação Adicional': 'dataNotificacaoAdicional',
    'Probabilidade de Perda': 'probabilidadePerda',
    'Data do valor provisionado': 'dataValorProvisionado',
    'Valor Provisionado': 'valorProvisionado',
    'Data do Andamento': 'dataAndamento',
    'Tipo do Andamento': 'tipoAndamento',
    'Descrição do Andamento': 'descricaoAndamento',
    'Complemento do Andamento': 'complementoAndamento',
    'Solicitante do Andamento': 'solicitanteAndamento',
    'Responsável do Andamento': 'responsavelAndamento',
    'Corresponsável do Andamento': 'corresponsavelAndamento',
    'Descrição do objeto': 'descricaoObjeto',
    'Escritório Credenciado': 'escritorioCredenciado',
    'Data da Contratação': 'dataContratacao',
    'Observação do Processo': 'observacaoDoProcesso',
    'Parecer do Processo': 'parecerDoProcesso',
}

# Presets por empresa
TODAY_STR = datetime.now().strftime('%d/%m/%Y')
EMPRESA_REGULAR = 'Direito Tributario'
COMPANY_PRESETS: Dict[str, Dict[str, object]] = {
    EMPRESA_REGULAR: {},
    'ENEL (RJ)': {
        'nomegrupo_id': '101',
        'solicitanteAndamento': '356',
        'responsavelAndamento': '353',
        'corresponsavelAndamento': '438',
        'prioridadeDe': '356',
        'orgao': 'TJ - RJ',
        'tipoEvento': '1035',
        'corresponsavel': '32',
        'solicitanteEvento': '356',
        'responsavelEvento': '353',
        'codlote': f'Enel {TODAY_STR}',
        'carteira': '101',
    },
    'STONE': {
        'nomegrupo_id': '49',
        'prioridadeDe': '102',
        'solicitanteAndamento': '102',
        'responsavelAndamento': '102',
        'corresponsavelAndamento': '102',
        'orgao': 'STJ',
        'corresponsavel': '30',
        'codlote': f'Stone {TODAY_STR}',
        'carteira': '49',
        'responsavelEvento': '102',
        'tipoEvento': '979',
        'solicitanteEvento': '102',
    },
    'CAGECE': {
        'nomegrupo_id': '6',
        'prioridadeDe': '135',
        'solicitanteAndamento': '135',
        'responsavelAndamento': '135',
        'corresponsavelAndamento': '135',
        'orgao': 'TJ - CE',
        'corresponsavel': '30',
        'codlote': f'Cagece {TODAY_STR}',
        'carteira': '6',
        'tipoEvento': '979',
        'responsavelEvento': '135',
        'solicitanteEvento': '135',
        'tipoAndamento': 'Não Informado',
    },
    'NOTREDAME – CÍVEL': {
        'nomegrupo_id': '21',
        'prioridadeDe': '431',
        'solicitanteAndamento': '99',
        'responsavelAndamento': '99',
        'corresponsavelAndamento': '99',
        'orgao': 'TJ - SP',
        'corresponsavel': '6',
        'codlote': f'NOTREDAME-CIVEL {TODAY_STR}',
        'carteira': '21',
        'tipoEvento': '380',
        'solicitanteEvento': '99',
        'tipoAndamento': 'Não Informado',
        'descricaoObjeto': 'Aviso prévio da rescisão posterior a 12 meses',
        'tipoObjeto': 'Aviso Prévio/Multa',
        'responsavelEvento': '99',
    },
    'NOTREDAME – ESTRATÉGICO': {
        'nomegrupo_id': '52',
        'prioridadeDe': '481',
        'solicitanteAndamento': '481',
        'responsavelAndamento': '481',
        'corresponsavelAndamento': '481',
        'orgao': 'TJ - SP',
        'corresponsavel': '33',
        'codlote': f'NOTREDAME-ESTRATEGICO {TODAY_STR}',
        'carteira': '52',
        'tipoEvento': '1049',
        'solicitanteEvento': '481',
        'tipoAndamento': 'Não Informado',
        'descricaoObjeto': 'Não Informado',
        'tipoObjeto': 'Aviso Prévio/Multa',
        'responsavelEvento': '481',
    },
    'NOTREDAME – TRABALHISTA': {
        'nomegrupo_id': '21',
        'prioridadeDe': '477',
        'solicitanteAndamento': '477',
        'responsavelAndamento': '477',
        'corresponsavelAndamento': '477',
        'orgao': 'TRT - 22º REGIAO',
        'corresponsavel': '31',
        'codlote': f'NOTREDAME-TRABALISTA {TODAY_STR}',
        'carteira': '48',
        'tipoEvento': '1002',
        'solicitanteEvento': '477',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '477',

    },
    'PORTO SEGURO': {
        'nomegrupo_id': '27',
        'prioridadeDe': '124',
        'solicitanteAndamento': '124',
        'responsavelAndamento': '124',
        'corresponsavelAndamento': '124',
        'orgao': 'TJ - SP',
        'corresponsavel': '7',
        'codlote': f'PORTOSEGURO {TODAY_STR}',
        'carteira': '27',
        'tipoEvento': '431',
        'solicitanteEvento': '124',
        'tipoAndamento': 'Não Informado',
        'descricaoObjeto': 'Aviso prévio da rescisão posterior a 12 meses',
        'tipoObjeto': 'Aviso Prévio/Multa',
        'responsavelEvento': '124',
    },
    'MOVIDA - PASSIVO ':{
        'nomegrupo_id': '62',
        'prioridadeDe':'341',
        'solicitanteAndamento': '341',
        'responsavelAndamento': '341',
        'corresponsavelAndamento': '341',
        'orgao': 'STJ',
        'corresponsavel': '5',
        'codlote': f'MOVIDA {TODAY_STR}',
        'carteira': '62',
        'tipoEvento': '1201',
        'solicitanteEvento': '341',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '341',
    },
    'ANCAR':{
        'nomegrupo_id': '3',
        'prioridadeDe':'140',
        'solicitanteAndamento': '140',
        'responsavelAndamento': '140',
        'corresponsavelAndamento': '140',
        'orgao': 'STJ',
        'corresponsavel': '2',
        'codlote': f'ANCAR {TODAY_STR}',
        'carteira': '3',
        'tipoEvento': '129',
        'solicitanteEvento': '140',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '140',
    },
    'PAGUE MENOS CIVEL':{
        'nomegrupo_id': '200',
        'prioridadeDe':'8',
        'solicitanteAndamento': '61',
        'responsavelAndamento': '61',
        'corresponsavelAndamento': '61',
        'orgao': 'STJ',
        'corresponsavel': '9',
        'codlote': f'PAGUE MENOS CIVEL {TODAY_STR}',
        'carteira': '29',
        'tipoEvento': '999',
        'solicitanteEvento': '61',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '8',

    },
    'PAGUE MENOS TRABALHISTA':{
        'nomegrupo_id': '200',
        'prioridadeDe':'479',
        'solicitanteAndamento': '227',
        'responsavelAndamento': '227',
        'corresponsavelAndamento': '227',
        'orgao': 'STJ',
        'corresponsavel': '15',
        'codlote': f'PAGUE MENOS TRABALHISTA {TODAY_STR}',
        'carteira': '35',
        'tipoEvento': '462',
        'solicitanteEvento': '227',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '479',
    },
    'AMBEV - CIVEL':{
        'nomegrupo_id': '1',
        'prioridadeDe':'63',
        'solicitanteAndamento': '63',
        'responsavelAndamento': '63',
        'corresponsavelAndamento': '63',
        'orgao': 'STJ',
        'corresponsavel': '1',
        'codlote': f'AMBEV - CIVEL {TODAY_STR}',
        'carteira': '1',
        'tipoEvento': '1',
        'solicitanteEvento': '63',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '63',
  },
    'RAIA DROGASIL ':{
        'nomegrupo_id': '59',
        'prioridadeDe':'63',
        'solicitanteAndamento': '63',
        'responsavelAndamento': '63',
        'corresponsavelAndamento': '63',
        'orgao': 'STJ',
        'corresponsavel': '42',
        'codlote': f'RAIA DROGASIL {TODAY_STR}',
        'carteira': '59',
        'tipoEvento': '1',
        'solicitanteEvento': '63',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '63',
  },
    'UNIP - CIVEL ':{
        'nomegrupo_id': '39',
        'prioridadeDe':'180',
        'solicitanteAndamento': '457',
        'responsavelAndamento': '457',
        'corresponsavelAndamento': '457',
        'orgao': 'STJ',
        'corresponsavel': '19',
        'codlote': f'UNIP- CIVEL {TODAY_STR}',
        'carteira': '39',
        'tipoEvento': '1010',
        'solicitanteEvento': '457',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '180',
  },
    'UNIP - CIVEL - ADM ':{
        'nomegrupo_id': '39',
        'prioridadeDe':'180',
        'solicitanteAndamento': '457',
        'responsavelAndamento': '457',
        'corresponsavelAndamento': '457',
        'corresponsavel': '19',
        'codlote': f'UNIP- CIVEL - ADM {TODAY_STR}',
        'carteira': '39',
        'tipoEvento': '1027',
        'solicitanteEvento': '457',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '180',
  },
    'UNIP - TRABALHISTA ':{
        'nomegrupo_id': '39',
        'prioridadeDe':'81',
        'solicitanteAndamento': '81',
        'responsavelAndamento': '81',
        'corresponsavelAndamento': '81',
        'orgao': 'TST',
        'corresponsavel': '19',
        'codlote': f'UNIP- TRABALHISTA {TODAY_STR}',
        'carteira': '119',
        'tipoEvento': '1032',
        'solicitanteEvento': '81',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '81',
  },
    'DIGITAL COLLEGE ':{
        'nomegrupo_id': '39',
        'prioridadeDe':'285',
        'solicitanteAndamento': '285',
        'responsavelAndamento': '285',
        'corresponsavelAndamento': '285',
        'orgao': 'STJ',
        'corresponsavel': '19',
        'codlote': f' DIGITAL COLLEGE {TODAY_STR}',
        'carteira': '39',
        'tipoEvento': '1010',
        'solicitanteEvento': '',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '285',
},
    'FGV ':{
        'nomegrupo_id': '39',
        'prioridadeDe':'285',
        'solicitanteAndamento': '285',
        'responsavelAndamento': '285',
        'corresponsavelAndamento': '285',
        'orgao': 'STJ',
        'corresponsavel': '19',
        'codlote': f' FGV {TODAY_STR}',
        'carteira': '39',
        'tipoEvento': '1010',
        'solicitanteEvento': '',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '285',
  },
    'GRAU TECNICO ':{
        'nomegrupo_id': '39',
        'prioridadeDe':'285',
        'solicitanteAndamento': '285',
        'responsavelAndamento': '285',
        'corresponsavelAndamento': '285',
        'orgao': 'STJ',
        'corresponsavel': '19',
        'codlote': f' GRAU TECNICO {TODAY_STR}',
        'carteira': '39',
        'tipoEvento': '1010',
        'solicitanteEvento': '',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '285',
  },
    'UNIGRANDE ':{
        'nomegrupo_id': '39',
        'prioridadeDe':'180',
        'solicitanteAndamento': '457',
        'responsavelAndamento': '457',
        'corresponsavelAndamento': '457',
        'orgao': 'STJ',
        'corresponsavel': '19',
        'codlote': f'UNIGRANDE {TODAY_STR}',
        'carteira': '39',
        'tipoEvento': '1010',
        'solicitanteEvento': '457',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '180',
  },
    'TRABALHISTA':{
        'nomegrupo_id': '40',
        'prioridadeDe':'483',
        'solicitanteAndamento': '438',
        'responsavelAndamento': '438',
        'corresponsavelAndamento': '438',
        'orgao': 'STJ',
        'corresponsavel': '23',
        'codlote': f'TRABALHISTA {TODAY_STR}',
        'carteira': '40',
        'tipoEvento': '590',
        'solicitanteEvento': '438',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '492',
    },
    'ITAPEVA':{
        'nomegrupo_id': '65',
        'prioridadeDe':'513',
        'solicitanteAndamento': '513',
        'responsavelAndamento': '56',
        'corresponsavelAndamento': '513',
        'orgao': 'STJ',
        'corresponsavel': '47',
        'codlote': f'ITAPEVA {TODAY_STR}',
        'carteira': '65',
        'tipoEvento': '1234',
        'solicitanteEvento': '513',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '513',
    },
    'SERVIÇOS':{
        'nomegrupo_id': '32',
        'prioridadeDe':'88',
        'solicitanteAndamento': '202',
        'responsavelAndamento': '202',
        'corresponsavelAndamento': '202',
        'orgao': 'STJ',
        'corresponsavel': '12',
        'codlote': f'SERVIÇOS {TODAY_STR}',
        'carteira': '32',
        'tipoEvento': '1238',
        'solicitanteEvento': '202',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '88',
    },
    'PUBLICO':{
        'nomegrupo_id': '55',
        'prioridadeDe':'201',
        'solicitanteAndamento': '201',
        'responsavelAndamento': '201',
        'corresponsavelAndamento': '201',
        'corresponsavel': '37',
        'codlote': f'PUBLICO {TODAY_STR}',
        'carteira': '55',
        'tipoEvento': '1084',
        'solicitanteEvento': '201',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '255',
    },
    'MOVIDA PASSIVO - ADM':{
        'nomegrupo_id': '62',
        'prioridadeDe':'519',
        'solicitanteAndamento': '19',
        'responsavelAndamento': '19',
        'corresponsavelAndamento': '19',
        'corresponsavel': '43',
        'codlote': f'MOVIDA PASSIVO - ADM {TODAY_STR}',
        'carteira': '62',
        'tipoEvento': '1211',
        'solicitanteEvento': '19',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '519',
    },
    'ORIGINAL PASSIVO':{
        'nomegrupo_id': '60',
        'prioridadeDe':'4',
        'solicitanteAndamento': '71',
        'responsavelAndamento': '71',
        'corresponsavelAndamento': '71',
        'corresponsavel': '44',
        'codlote': f'ORIGINAL PASSIVO {TODAY_STR}',
        'carteira': '60',
        'tipoEvento': '1192',
        'solicitanteEvento': '71',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '4',
    },
    'AMBEV - TRAB':{
        'nomegrupo_id': '1',
        'prioridadeDe':'386',
        'solicitanteAndamento': '227',
        'responsavelAndamento': '227',
        'corresponsavelAndamento': '227',
        'corresponsavel': '18',
        'codlote': f'AMBEV - TRAB {TODAY_STR}',
        'carteira': '36',
        'tipoEvento': '39',
        'solicitanteEvento': '227',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '386',
     },
    'COBRANÇA JUDICIAL':{
        'nomegrupo_id': '41',
        'prioridadeDe':'557',
        'solicitanteAndamento': '245',
        'responsavelAndamento': '245',
        'corresponsavelAndamento': '245',
        'corresponsavel': '24',
        'codlote': f'COBRANÇA JUDICIAL {TODAY_STR}',
        'carteira': '41',
        'tipoEvento': '582',
        'solicitanteEvento': '245',
        'tipoAndamento': 'Não Informado',
        'responsavelEvento': '557',
    },
}

COMMON_DEFAULTS = {
    'tipoPoloCliente': 'Passivo',
    'codpolo_cliente': '2',
    'dataNotificacao': 'Agora',
    'dataNotificacaoAdicional': 'No dia do Evento',
    'escritorioCredenciado': 'VALENÇA & ASSOCIADOS',
    'usuario_submit_id': '420',
    'verificado': 0,
    'exportado': 0,
}

# Colunas da planilha que podem faltar sem bloquear a importacao.
OPTIONAL_INPUT_DEFAULTS = {
    'numeroUnidade': None,
    'unidade': '',
    'especialidade': '',
    'comarca': '',
    'estado': '',
    'materia': '',
    'tipoInstancia': '',
}

OPTIONAL_INPUT_COLUMNS = set(OPTIONAL_INPUT_DEFAULTS)

# Campos de texto que limitaremos a 255 caracteres
CAMPOS_TEXTO_255 = [
    'partePoloAtivo','partePoloPassivo','cliente','tipoDeRito','unidade','especialidade',
    'comarca','estado','orgao','natureza','materia','tipoInstancia','tipoAcao','tipoObjeto',
    'fase','status','carteira','prioridadeDe','tipoEvento','solicitanteEvento','responsavelEvento',
    'corresponsavel','sistemaExterno','tipoAndamento','solicitanteAndamento','responsavelAndamento',
    'corresponsavelAndamento','descricaoObjeto','escritorioCredenciado','tipoPoloCliente','tipo_resultado',
    'Adv_parte_contraria'
]

COLUNAS_DATA = [
    'dataDistribuicao','dataInstancia','dataFase','dataStatus','dataEvento','dataValorProvisionado',
    'dataAndamento','dataContratacao','data_resultado'
]
